AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics:
  Enabled: false

# There's if statement in the Gemfile
Bundler/DuplicatedGem:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Style/NumericLiterals:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ParenthesesAroundCondition:
  Enabled: false

Layout/LineLength:
  Max: 130
