name: CI
on: [push, pull_request]
jobs:
  rufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle lock --update
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup
        run: bundle install --jobs=3 --retry=3
      - name: Run rufo
        run: bundle exec rake rufo:check
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle lock --update
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup
        run: bundle install --jobs=3 --retry=3
      - name: Run rubocop
        run: bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    needs: [rufo, rubocop]
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.5, 2.6, 2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Setup Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle lock --update
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup
        run: bundle install --jobs=3 --retry=3
      - name: Run rubocop
        run: bundle exec rake test
